version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: libropen_db_local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=libropen_local
    ports:
      - "5432:5432"
